"""add user profile fields

Revision ID: 5647ad3ab9f7
Revises: 9d8914e378cf
Create Date: 2026-09-29 09:07:51.146415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5647ad3ab9f7'
down_revision: Union[str, Sequence[str], None] = '9d8914e378cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('pending_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_change_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('email_change_code_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_change_code_expires')
    op.drop_column('users', 'email_change_code')
    op.drop_column('users', 'pending_email')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
